# Étape 1 : Compilation  
FROM maven:3.9.4-eclipse-temurin-17 as build  
WORKDIR /app  
COPY . .  

RUN mvn clean package -Dtest='!DemoApplicationTests'  
  
# Étape 2 : Image finale  
FROM openjdk:17-jdk-slim  
WORKDIR /app  
COPY --from=build /app/target/*.jar app.jar  
EXPOSE 8080  
ENTRYPOINT ["java", "-jar", "app.jar"]