name: CI Pipeline for Spring Boot with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: {{javaVersion}}
  WORKING_DIR: {{workingDirectory}}

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make mvnw executable
        run: chmod +x ./mvnw
        working-directory: ${{ env.WORKING_DIR }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ env.JAVA_VERSION }}-${{ hashFiles('**/${{ env.WORKING_DIR }}/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.JAVA_VERSION }}-
            ${{ runner.os }}-maven-

      - name: Run tests
        run: ./mvnw clean test -B
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build application
        run: ./mvnw package -B -DskipTests
        working-directory: ${{ env.WORKING_DIR }}
